---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kodpi.
--- DateTime: 02.04.2022 20:48
---
function CastCircleOfHealing()
    local target = GetSpellTargetUnit()

    local mana = GetUnitState(PRIEST, UNIT_STATE_MANA) * 0.21
    SetUnitState(PRIEST, UNIT_STATE_MANA, GetUnitState(PRIEST, UNIT_STATE_MANA) - mana)

    local heal = GetRandomInt(958, 1058)
    bj_groupCountUnits()
    SetUnitState(target, UNIT_STATE_LIFE, GetUnitState(target, UNIT_STATE_LIFE) + heal)
    print(heal)
end

function IsCircleOfHealing()
    return GetSpellAbilityId() == CIRCLE_OF_HEALING
end

function Init_CircleOfHealing()
    local trigger_ability = CreateTrigger()
    TriggerRegisterPlayerUnitEvent(trigger_ability, Player(0), EVENT_PLAYER_UNIT_SPELL_CAST, nil)
    TriggerAddCondition(trigger_ability, Condition(IsCircleOfHealing))
    TriggerAddAction(trigger_ability, CastCircleOfHealing)
end