---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kodpi.
--- DateTime: 02.04.2022 20:48
---
function CastCircle_Of_Healing()
    local target = GetSpellTargetUnit()

    local mana = GetUnitState(PRIEST, UNIT_STATE_MANA) * 0.21
    SetUnitState(PRIEST, UNIT_STATE_MANA, GetUnitState(PRIEST, UNIT_STATE_MANA) - mana)

    local heal = GetRandomInt(958, 1058)
    bj_groupCountUnits()
    SetUnitState(target, UNIT_STATE_LIFE, GetUnitState(target, UNIT_STATE_LIFE) + heal)
    print(heal)
end

function IsCircle_Of_Healing()
    return GetSpellAbilityId() == CIRCLE_OF_HEALING
end

function Init_Circle_Of_Healing()
    local trigger_ability = CreateTrigger()
    TriggerRegisterPlayerUnitEvent(trigger_ability, Player(0), EVENT_PLAYER_UNIT_SPELL_CAST, nil)
    TriggerAddCondition(trigger_ability, Condition(IsCircle_Of_Healing))
    TriggerAddAction(trigger_ability, CastCircle_Of_Healing)
end