---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kodpi.

function RemoveHeal15(target)

    local tm = CreateTimer()

    TimerStart(tm, 3., false, Reviewheal3 (target))
    TimerStart(tm, 3., false, Reviewheal3 (target))
    TimerStart(tm, 3., false, Reviewheal3 (target))
    TimerStart(tm, 3., false, Reviewheal3 (target))
    TimerStart(tm, 3., false, Reviewheal3 (target))
end

function RemoveHeal3(target)
    local heal = 280
    SetUnitState(target, UNIT_STATE_LIFE, GetUnitState(target, UNIT_STATE_LIFE) + heal)
end

function CastRenew()

    local target = GetSpellTargetUnit()


    local tm = CreateTimer()
    TimerStart(tm, 15., false, RemoveHeal15(target))

    local mana = GetUnitState(PRIEST, UNIT_STATE_MANA) * 0.17
    SetUnitState(PRIEST, UNIT_STATE_MANA, GetUnitState(PRIEST, UNIT_STATE_MANA) - mana)

end

function IsRenew()
    return GetSpellAbilityId() == FLASH_HEAL
end

function Init_Renew()
    local trigger_ability = CreateTrigger()
    TriggerRegisterPlayerUnitEvent(trigger_ability, Player(0), EVENT_PLAYER_UNIT_SPELL_CAST, nil)
    TriggerAddCondition(trigger_ability, Condition(IsRenew))
    TriggerAddAction(trigger_ability, CastRenew)
end