
define 
{  
    /* Lord Marrowgar */
    COLDFLAME = 'A001'
    WHIRLWIND = 'A005'

    /* Paladin */
    CONSECRATION = 'A009'
    CONSECRATION_TR = 'A00A'
    HAMMER_RIGHTEOUS = 'A00B'
    GREATER_BLESSING_KINGS = 'A00C'
    GREATER_BLESSING_SANCTUARY = 'A00F'
}