
define 
{  
    /* Lord Marrowgar */
    COLDFLAME = 'A001'
    WHIRLWIND = 'A005'

    /* Paladin */
    CONSECRATION = 'A009'
    CONSECRATION_TR = 'A00A'
    HAMMER_RIGHTEOUS = 'A00B'
    GREATER_BLESSING_KINGS = 'A00C'
    GREATER_BLESSING_SANCTUARY = 'A00H'
    CRUSADER_AURA = 'A00J'
    GREATER_BLESSING_WISDOM = 'A00F'
    GREATER_BLESSING_WISDOM_TR = 'A00G'
}